# Generated by Django 4.0.1 on 2022-01-23 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Default',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=300)),
                ('valor', models.FloatField()),
                ('data', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='despesa',
            name='data',
        ),
        migrations.RemoveField(
            model_name='despesa',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='despesa',
            name='id',
        ),
        migrations.RemoveField(
            model_name='despesa',
            name='valor',
        ),
        migrations.RemoveField(
            model_name='receita',
            name='data',
        ),
        migrations.RemoveField(
            model_name='receita',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='receita',
            name='id',
        ),
        migrations.RemoveField(
            model_name='receita',
            name='valor',
        ),
        migrations.AddField(
            model_name='despesa',
            name='default_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.default'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receita',
            name='default_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.default'),
            preserve_default=False,
        ),
    ]
