# Generated by Django 4.0.1 on 2022-02-05 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_default_remove_despesa_data_remove_despesa_descricao_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Despesa',
            new_name='Expense',
        ),
        migrations.RenameModel(
            old_name='Receita',
            new_name='Income',
        ),
        migrations.RenameField(
            model_name='default',
            old_name='data',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='default',
            old_name='descricao',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='default',
            old_name='valor',
            new_name='value',
        ),
    ]
